name: 'Terraform'

on: [push, pull_request]

env:
  TF_LOG: INFO

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    # Set the working directory to main for the config files
    defaults:
      run:
        shell: bash
#         working-directory: ./main

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2

    # Install the preferred version of Terraform CLI 
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.3.7
    - name: Terraform Init
      id: init
#       env:
#         ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
#         ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
#         ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
#         ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
#         RESOURCE_GROUP: ${{ secrets.RESOURCE_GROUP }}
#         STORAGE_ACCOUNT: ${{ secrets.STORAGE_ACCOUNT }}
#         CONTAINER_NAME: ${{ secrets.CONTAINER_NAME }}
      run: terraform init    
      
    - name: Terraform Fmt
      id: fmt
      run: terraform fmt
      
    - name: Terraform Validate
      id: validate
      run: terraform validate
    
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      env:
        role-to-assume: arn:aws:iam::773914189848:user/sregmi
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}

#         aws-region: us-east-1
    
    - name: Terraform Plan
      id: plan
#       env:
#           AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: terraform plan --out tfplan.binary

    - name: Terraform Show
      id: show
      run: terraform show -json tfplan.binary > tfplan.json
      
    
